from pathlib import Path
from starlette.config import Config

config = Config(".env")

DEBUG = config("DEBUG", cast=bool, default=False)

HTTPS_ONLY = config("HTTPS_ONLY", cast=bool, default=True)

SECRET = config("SECRET", cast=str)

BASE_DIR = Path(__file__).parent

TEMPLATES_DIR = BASE_DIR / "templates"

STATIC_DIR = BASE_DIR / "static"

CLIENT = {
    "api_key": "aar-dev",
    "title": "Aarhus Teaters Arkiv",
    "name": "aarhusteater",
    "description": "Aarhus Teater arkiv og historie",
    "host": "https://aarhusteaterarkiv-web.appspot.com",
    # Contact info
    "homepage": "https://www.aarhusteater.dk/om-teatret/om-huset/",
    "telephone": "+45 89 33 23 59",
    "mail": "arkivar@aarhusteater.dk",
    "address": "Teatergaden 1, 8000 Aarhus C",
    "map": "https://www.openstreetmap.org/way/51265304",
    "facebook": "https://www.facebook.com/Teaterarkivaren",
    # View settings
    "excluded_query_params": [],
    "excluded_keys": [
        "identification",
        "admin_tags",
        "organisations",
        "programme",
        "poster",
        "curators",
        "locations",
    ],
    # Query settings
    "curator": "Aarhus Teater Arkiv",
    "default_query_params": [("curators", "4")],
    "collections": [
        "records",
        "events",
        "people",
        "organisations",
        "poster",
        "programme",
        "collections",
        "creators",
        "relations",
    ],
    "facets": [
        {
            "facet_label": "Forestillinger",
            "facet_field": "series",
            "facet_file": "static/json/structure.json",
        }
    ],
    "filters": {
        "creators": {
            "display_label": "Skaber",
            "repeatable": True,
            "type": "integer",
            "endpoint": "creators",
            "filter": True,
        },
        "locations": {
            "display_label": "Stedsangivelse",
            "repeatable": True,
            "type": "integer",
            "endpoint": "locations",
            "filter": True,
        },
        "events": {
            "display_label": "Forestilling",
            "repeatable": True,
            "type": "integer",
            "endpoint": "events",
            "filter": True,
        },
        "people": {
            "display_label": "Person",
            "repeatable": True,
            "type": "integer",
            "endpoint": "people",
            "filter": True,
        },
        "organisations": {
            "display_label": "Organisation",
            "repeatable": True,
            "type": "integer",
            "endpoint": "organisations",
            "filter": True,
        },
        "collection": {
            "display_label": "Samling",
            "repeatable": False,
            "type": "integer",
            "endpoint": "collections",
            "filter": True,
        },
        "start_date": {
            "display_label": "Startdato",
            "repeatable": False,
            "type": "string",
            "endpoint": "literal",
            "filter": True,
        },
        "end_date": {
            "display_label": "Slutdato",
            "repeatable": False,
            "type": "string",
            "endpoint": "literal",
            "filter": True,
        },
        "subjects": {
            "display_label": "Emnekategori",
            "repeatable": True,
            "type": "integer",
            "endpoint": "subjects",
            "filter": True,
        },
        "series": {
            "display_label": "Serie",
            "repeatable": False,
            "type": "string",
            "endpoint": "literal",
            "filter": True,
        },
        "tags": {
            "display_label": "Tag",
            "repeatable": True,
            "type": "integer",
            "endpoint": "tags",
            "filter": True,
        },
        "collection_tags": {
            "display_label": "Samlingstags",
            "repeatable": True,
            "type": "string",
            "endpoint": "literal",
            "filter": True,
        },
        "content_type": {
            "display_label": "Arkivalietype",
            "repeatable": False,
            "type": "integer",
            "endpoint": "content_types",
            "filter": True,
        },
        "content_types": {
            "display_label": "Arkivalietype",
            "repeatable": True,
            "type": "integer",
            "endpoint": "content_types",
            "filter": True,
        },
        "license": {
            "display_label": "Brugslicens",
            "repeatable": False,
            "type": "integer",
            "endpoint": "licenses",
            "filter": True,
        },
        "online_only": {
            "display_label": "Kun online arkivalier",
            "repeatable": False,
            "type": "boolean",
            "endpoint": "system",
            "filter": True,
        },
        "limit": {
            "display_label": "Hits per side",
            "repeatable": False,
            "type": "literal",
            "endpoint": "system",
            "filter": False,
        },
        "admin_tags": {
            "display_label": "Administrative tags",
            "repeatable": True,
            "type": "string",
            "endpoint": "literal",
            "filter": True,
        },
    },
}

TEMPLATE_GLOBALS = {
    "translate": {
        "identification": "Identifikation",
        "identifier": "Arkivalie ID",
        "ingest_id": "Indkomst ID",
        "related_content": "Relateret arkivalie",
        "curators": "Kuratorer",
        "administration": "Administration",
        "aggrement": "Afleveringsaftale",
        "rightsholders": "Rettighedshavere",
        "copyright_expires": "Copyright udløber (år)",
        "declassification_expires": "Persondata udløber (år)",
        "original_id": "Originalt id",
        "admin_tags": "Administrative tags",
        "admin_notes": "Administrative noter",
        "admin_data": "Administrative data",
        "description": "Beskrivelse",
        "title": "Titel",
        "content_type": "Arkivalietype",
        "collection": "Samling",
        "hierarchical_level": "Arkivserie",
        "series": "Arkivserie",
        "abstract": "Abstrakt",
        "subjects": "Emner",
        "start_date": "Startdato",
        "end_date": "Slutdato",
        "creators": "Skaber",
        "textcontent": "Tekst",
        "collection_tags": "Originale emner",
        "desc_notes": "Noter",
        "desc_data": "Beskrivelsesdata",
        "entities": "Relationer",
        "tags": "Tags",
        "people": "Personer",
        "events": "Forestillinger",
        "licenses": "Brugslicenser",
        "collections": "Samlinger",
        "records": "Arkivalier",
        "people": "Personer",
        "organisations": "Organisationer",
        "events": "Forestillinger",
        "locations": "Steder",
        "digital_content": "Digitalt indhold",
        "checksum": "Checksum",
        "checksum_algorithm": "Checksum-algoritme",
        "last_checksum_date": "Sidste chemsumdato",
        "original_filename": "Originalt filnavn",
        "filename": "Filnavn",
        "mimetype": "Mimetype",
        "digital_size": "Digital størrelse",
        "digital_format": "Digitalt format",
        "filelist": "Indholdsfortegnelse",
        "representations": "Webressourcer",
        "small_size_url": "Frimærke",
        "medium_size_url": "Medium størrelse",
        "large_size_url": "Stor størrelse",
        "download_url": "Link til original fil",
        "analog_content": "Analog indhold",
        "storage_id": "ArkivID/Løbenummer",
        "physical_extent": "Fysisk mængde",
        "storage_room": "Rum",
        "storage_rack": "Reol",
        "storage_unit": "Fag",
        "storage_shelf": "Hylde",
        "physical_condition": "Fysisk tilstand",
        "physical_size": "Fysisk størrelse",
        "physical_format": "Fysisk format",
        "entity_id": "ID",
        "id": "Id",
        "display_name": "Displaynavn",
        "gender": "Køn",
        "place_of_birth": "Fødselssted",
        "date_of_birth": "Fødselsdato",
        "place_of_death": "Dødssted",
        "date_of_death": "Dødsdato",
        "birthname": "Pigenavn (født)",
        "sources": "Kilder",
        "firstnames": "Fornavne",
        "lastnames": "Mellem- og efternavne",
        "portrait": "Portræt",
        "occupation": "Beskæftigelse",
        "industry": "Branche",
        "from_date": "Startdato",
        "to_date": "Slutdato",
        "name": "Navn",
        "named_date": "Navngivt år",
        "zipcode": "Postnummer",
        "longitude": "Breddegrad",
        "latitude": "Længdegrad",
        "rotation": "Rotation",
        "event_type": "Begivenhedstype",
        "notes": "Introduktion",
        "extend": "Omfang",
        "structure": "Struktur",
        "link": "Licenstekst",
    }
}
